//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqPractice
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockDBEntities : DbContext
    {
        public StockDBEntities()
            : base("name=StockDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<日收盤> 日收盤 { get; set; }
        public virtual DbSet<代號表指數> 代號表指數 { get; set; }
        public virtual DbSet<交易所產業分類代號表> 交易所產業分類代號表 { get; set; }
    }
}
