//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class 交易所產業分類代號表
    {
        public string 代號 { get; set; }
        public string 名稱 { get; set; }
        public int 市場別 { get; set; }
        public string 市場別名稱 { get; set; }
        public Nullable<short> 掛牌數 { get; set; }
        public string 指數代號 { get; set; }
        public string 指數名稱 { get; set; }
        public Nullable<System.DateTime> CTIME { get; set; }
        public Nullable<System.DateTime> MTIME { get; set; }
    }
}
