//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class 代號表指數
    {
        public string 代號 { get; set; }
        public string 名稱 { get; set; }
        public string 英文名稱 { get; set; }
        public string 種類 { get; set; }
        public string 代表號 { get; set; }
        public string 交易所產業編號 { get; set; }
        public string 整併後交易所產業編號 { get; set; }
        public string 備註 { get; set; }
        public string C200707交易所產業編號 { get; set; }
        public string C200707整併後交易所產業編號 { get; set; }
        public string C200707備註 { get; set; }
        public string 權證標的用代號 { get; set; }
        public string 權證標的用名稱 { get; set; }
        public string 參考名稱1 { get; set; }
        public string 參考名稱2 { get; set; }
        public string 參考名稱3 { get; set; }
        public Nullable<bool> 啟用 { get; set; }
        public Nullable<System.DateTime> CTIME { get; set; }
        public Nullable<System.DateTime> MTIME { get; set; }
    }
}
