//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class 日收盤
    {
        public Nullable<System.DateTime> CTIME { get; set; }
        public Nullable<int> MTIME { get; set; }
        public Nullable<long> RecordID { get; set; }
        public string 日期 { get; set; }
        public string 股票代號 { get; set; }
        public string 股票名稱 { get; set; }
        public Nullable<decimal> 參考價 { get; set; }
        public Nullable<decimal> 開盤價 { get; set; }
        public Nullable<decimal> 最高價 { get; set; }
        public Nullable<decimal> 最低價 { get; set; }
        public Nullable<decimal> 收盤價 { get; set; }
        public Nullable<decimal> 漲跌 { get; set; }
        public string 上市櫃 { get; set; }
        public string 產業代號 { get; set; }
        public Nullable<decimal> 漲停價 { get; set; }
        public Nullable<decimal> 跌停價 { get; set; }
        public string 漲跌狀況 { get; set; }
        public Nullable<decimal> 最後委買價 { get; set; }
        public Nullable<decimal> 最後委賣價 { get; set; }
        public Nullable<decimal> 漲幅___ { get; set; }
        public Nullable<decimal> 振幅___ { get; set; }
        public Nullable<long> 成交量 { get; set; }
        public Nullable<long> 成交量_股_ { get; set; }
        public Nullable<long> 成交筆數 { get; set; }
        public Nullable<long> 成交金額_千_ { get; set; }
        public Nullable<decimal> 成交值比重___ { get; set; }
        public Nullable<decimal> 成交量變動___ { get; set; }
        public Nullable<decimal> 股本_百萬_2 { get; set; }
        public Nullable<decimal> 均張變動___ { get; set; }
        public Nullable<decimal> 均張 { get; set; }
        public Nullable<decimal> 總市值_億_ { get; set; }
        public Nullable<decimal> 市值比重___ { get; set; }
        public Nullable<decimal> 類股本益比 { get; set; }
        public Nullable<decimal> 類股股價淨值比 { get; set; }
        public Nullable<decimal> 類股股價淨值比2 { get; set; }
        public Nullable<decimal> 本益比 { get; set; }
        public Nullable<decimal> 本益比_近四季_ { get; set; }
        public Nullable<decimal> 股東權益_百萬_ { get; set; }
        public Nullable<decimal> 股價淨值比 { get; set; }
        public Nullable<decimal> 股價淨值比2 { get; set; }
        public Nullable<float> 舊股本_百萬_ { get; set; }
        public Nullable<int> 委買張數 { get; set; }
        public Nullable<int> 委賣張數 { get; set; }
        public Nullable<decimal> 次日參考價 { get; set; }
        public Nullable<long> 成交金額_元 { get; set; }
        public Nullable<decimal> 均價 { get; set; }
        public Nullable<decimal> 股本_百萬_ { get; set; }
        public Nullable<decimal> 週轉率 { get; set; }
        public Nullable<short> 漲跌停 { get; set; }
    }
}
